import requests

TOKEN = "YOUR_TELEGRAM_TOKEN"
CHAT_ID = "-1003889484238"
THREAD_ID = 50

def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    data = {
        "chat_id": CHAT_ID,
        "message_thread_id": THREAD_ID,
        "text": text
    }
    requests.post(url, data=data)

try:

    btc = requests.get(
        "https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT"
    ).json()

    btc_price = btc["price"]

    gold = requests.get(
        "https://api.metals.live/v1/spot/gold"
    ).json()

    gold_price = gold[0]["price"]

    message = f"""
DAILY MARKET UPDATE

• Asset: XAUUSD
• Price: {gold_price}

• Asset: BTCUSD
• Price: {btc_price}

Generated by: The 1% Elite Traders Circle
"""

    send_message(message)

except Exception as e:
    print("Error:", e)
