import requests

TOKEN = "YOUR_NEW_TOKEN"
CHAT_ID = "-1003889484238"
THREAD_ID = 50

def send_message(text):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    data = {
        "chat_id": CHAT_ID,
        "message_thread_id": THREAD_ID,
        "text": text
    }
    requests.post(url, data=data)

btc = requests.get("https://api.coindesk.com/v1/bpi/currentprice/USD.json").json()
btc_price = btc["bpi"]["USD"]["rate"]

gold = requests.get("https://api.metals.live/v1/spot/gold").json()
gold_price = gold[0]["price"]

message = f"""
DAILY MARKET UPDATE

• Asset: XAUUSD
• Price: {gold_price}

• Asset: BTCUSD
• Price: {btc_price}

Generated by: The 1% Elite Traders Circle
"""

send_message(message)
